name: Cloudflare Pages Deploy

on:
  repository_dispatch:
    types: [CloudflarePagesDeploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - id: create-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.TOKEN_APP_ID }}
          private-key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}
          owner: ${{ github.event.client_payload.owner }}

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: '${{ github.event.client_payload.owner }}/${{ github.event.client_payload.repo }}'
          token: ${{ steps.create-token.outputs.token }}

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Cloudflare
        run: npx --yes wrangler pages deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_PAGES_API }}
