name: Cloudflare Pages Deploy

on:
  repository_dispatch:
    types: [CloudflarePagesDeploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Mask all payload values
        run: |
          payload='${{ toJson(github.event.client_payload) }}'
          
          echo "$payload" | jq -r 'to_entries | .[] | "::add-mask::\(.value)"' | while read -r line; do
            echo "$line"
          done

      - id: create-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.TOKEN_APP_ID }}
          private-key: ${{ secrets.TOEKN_APP_PRIVATE_KEY }}

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: '${{ github.event.client_payload.repository }}'
          token: ${{ steps.create-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API }}
          command: pages deploy ${{ github.event.client_payload.build }} --project-name=${{ github.event.client_payload.project }}
